from dataclasses import dataclass
from typing import Any, Self

from ddd.file_checker.domain.enums import (
    FileCheckerHashAlgorithmEnum,
    FileCheckerRequestKeyEnum,
)


@dataclass(frozen=True, slots=True)
class VerifyFileSignatureDto:
    """Input DTO for file signature verification use case.

    Pure data transport — immutable container for request data.
    The __init__ is auto-generated by @dataclass with typed parameters.
    Access fields directly: dto.file_path, dto.expected_hash, dto.algorithm.

    Attributes:
        file_path: Path to the file to verify.
        expected_hash: Expected hash value in lowercase hex.
        algorithm: Hash algorithm name (default: sha256).

    Note: Validation is NOT the DTO's responsibility. The Service validates
    business rules via VerifyFileSignatureService._fail_if_wrong_input().
    """

    file_path: str
    expected_hash: str
    algorithm: str = FileCheckerHashAlgorithmEnum.SHA256

    @classmethod
    def from_primitives(cls, primitives: dict[str, Any]) -> Self:
        """Factory — construct from external data (request, user input, etc).

        Responsibility: Type casting and basic cleaning (trim, lowercase, coerce).
        NOT responsible: Business validation or domain rules.

        Args:
            primitives: Dict with file_path, expected_hash, algorithm keys.

        Returns:
            VerifyFileSignatureDto instance.
        """
        file_path = str(
            primitives.get(FileCheckerRequestKeyEnum.FILE_PATH, "")
        ).strip()
        expected_hash = str(
            primitives.get(FileCheckerRequestKeyEnum.EXPECTED_HASH, "")
        ).strip().lower()
        algorithm = str(primitives.get(
            FileCheckerRequestKeyEnum.ALGORITHM,
            FileCheckerHashAlgorithmEnum.SHA256.value)
        ).strip().lower()

        return cls(
            file_path=file_path,
            expected_hash=expected_hash,
            algorithm=algorithm,
        )
