from enum import StrEnum
from typing import final


@final
class EnvvarsKeysEnum(StrEnum):
    """Environment variable keys used by the application."""

    AZURE_API_VERSION = "AZURE_API_VERSION"
    AZURE_ORGANIZATION_NAME = "AZURE_ORGANIZATION_NAME"
    AZURE_PAT = "AZURE_PAT"

    APP_DEFAULT_PROJECT = "APP_DEFAULT_PROJECT"
    APP_LOG_PATH = "APP_LOG_PATH"

    SHAREPOINT_CLIENT_ID = "SHAREPOINT_CLIENT_ID"
    SHAREPOINT_CLIENT_SECRET = "SHAREPOINT_CLIENT_SECRET"
    SHAREPOINT_TENANT_ID = "SHAREPOINT_TENANT_ID"
    SHAREPOINT_SITE_ID = "SHAREPOINT_SITE_ID"

    LOCAL_DOCKER_LAMP_PATH = "LOCAL_DOCKER_LAMP_PATH"
    LOCAL_WWW_PATH = "LOCAL_WWW_PATH"
    LOCAL_VHOSTS_FILE = "LOCAL_VHOSTS_FILE"
    LOCAL_HOSTS_FILE = "LOCAL_HOSTS_FILE"
    LOCAL_BASE_ENV_FILE = "LOCAL_BASE_ENV_FILE"