version: '3.8'

services:
  api:
    build: .
    ports:
      - "8123:8123"
    environment:
      - APP_ENV=development
      - DATABASE_URL=postgresql://user:password@postgres:5432/antiphishing
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8123 --reload

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=antiphishing
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: