version: "3.9"

services:
  python36:
    container_name: cont-py38
    hostname: py38
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    # entrypoint: /usr/src/entrypoint.sh # da un error y tira el contenedor
    volumes:
      - ./pyprint:/usr/src/pyprint

    # debug vscode
    ports:
       - "8080:8080"
    # mantiene el contenedor en ejecución
    # command: tail -f /dev/null toma 10 segundos en parar el contenedor
    tty: true #toma 2 segundos en parar el contenedor

    networks:
      - pyprintnet

networks:
  pyprintnet:
      name: pyprintnet
